export default [
  {
    id: 65361,
    gene_id: 23066,
    gene_symbol: 'CAND2',
    dsi: 0.792,
    dpi: 0.423,
    disease_id: 'C0004238',
    disease_name: 'Atrial Fibrillation',
    disease_type: 'disease',
    disease_class: 'C23;C14',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.42,
    ei: 1,
    year_initial: 2016,
    year_final: 2018,
    nof_pmids: 2,
    nof_snps: 2,
    source: 'CTD_human'
  },
  {
    id: 65362,
    gene_id: 23066,
    gene_symbol: 'CAND2',
    dsi: 0.792,
    dpi: 0.423,
    disease_id: 'C0235480',
    disease_name: 'Paroxysmal atrial fibrillation',
    disease_type: 'disease',
    disease_class: 'C23;C14',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.3,
    ei: 1,
    year_initial: 2018,
    year_final: 2018,
    nof_pmids: 2,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 65363,
    gene_id: 23066,
    gene_symbol: 'CAND2',
    dsi: 0.792,
    dpi: 0.423,
    disease_id: 'C2585653',
    disease_name: 'Persistent atrial fibrillation',
    disease_type: 'phenotype',
    disease_class: 'C23;C14',
    disease_semantic_type: 'Pathologic Function',
    score: 0.3,
    ei: 1,
    year_initial: 2018,
    year_final: 2018,
    nof_pmids: 2,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 65364,
    gene_id: 23066,
    gene_symbol: 'CAND2',
    dsi: 0.792,
    dpi: 0.423,
    disease_id: 'C3468561',
    disease_name: 'familial atrial fibrillation',
    disease_type: 'phenotype',
    disease_class: 'C23;C14',
    disease_semantic_type: 'Pathologic Function',
    score: 0.3,
    ei: 1,
    year_initial: 2018,
    year_final: 2018,
    nof_pmids: 2,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 66661,
    gene_id: 23639,
    gene_symbol: 'LRRC6',
    dsi: 0.659,
    dpi: 0.538,
    disease_id: 'C0022521',
    disease_name: 'Kartagener Syndrome',
    disease_type: 'disease',
    disease_class: 'C16;C08;C09;C14',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.33,
    ei: 1,
    year_initial: 2012,
    year_final: 2013,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'ORPHANET'
  },
  {
    id: 66662,
    gene_id: 23639,
    gene_symbol: 'LRRC6',
    dsi: 0.659,
    dpi: 0.538,
    disease_id: 'C3543826',
    disease_name: 'CILIARY DYSKINESIA, PRIMARY, 19',
    disease_type: 'disease',
    disease_class: '',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.9,
    ei: 1,
    year_initial: 2012,
    year_final: 2016,
    nof_pmids: 3,
    nof_snps: 10,
    source: 'CTD_human;GENOMICS_ENGLAND;UNIPROT'
  },
  {
    id: 66663,
    gene_id: 23639,
    gene_symbol: 'LRRC6',
    dsi: 0.659,
    dpi: 0.538,
    disease_id: 'C4317124',
    disease_name: 'Polynesian Bronchiectasis',
    disease_type: 'disease',
    disease_class: 'C16;C08;C09;C14',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.3,
    ei: 1,
    year_initial: 2012,
    year_final: 2012,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'ORPHANET'
  },
  {
    id: 66664,
    gene_id: 23639,
    gene_symbol: 'LRRC6',
    dsi: 0.659,
    dpi: 0.538,
    disease_id: 'C4551720',
    disease_name: 'Primary Ciliary Dyskinesia',
    disease_type: 'disease',
    disease_class: 'C16;C08;C09',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.56,
    ei: 0.833,
    year_initial: 2012,
    year_final: 2018,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'GENOMICS_ENGLAND;ORPHANET'
  },
  {
    id: 66665,
    gene_id: 23639,
    gene_symbol: 'LRRC6',
    dsi: 0.659,
    dpi: 0.538,
    disease_id: 'C4551906',
    disease_name: 'Ciliary Dyskinesia, Primary, 1, With Or Without Situs Inversus',
    disease_type: 'disease',
    disease_class: 'C16;C08;C09;C14',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.4,
    ei: 1,
    year_initial: 2012,
    year_final: 2014,
    nof_pmids: 1,
    nof_snps: 1,
    source: 'ORPHANET'
  },
  {
    id: 24644,
    gene_id: 3148,
    gene_symbol: 'HMGB2',
    dsi: 0.615,
    dpi: 0.615,
    disease_id: 'C0028754',
    disease_name: 'Obesity',
    disease_type: 'disease',
    disease_class: 'C23;C18',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.3,
    ei: 1,
    year_initial: 2011,
    year_final: 2011,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 24645,
    gene_id: 3148,
    gene_symbol: 'HMGB2',
    dsi: 0.615,
    dpi: 0.615,
    disease_id: 'C0033578',
    disease_name: 'Prostatic Neoplasms',
    disease_type: 'group',
    disease_class: 'C04;C12',
    disease_semantic_type: 'Neoplastic Process',
    score: 0.3,
    ei: 1,
    year_initial: 2018,
    year_final: 2018,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 24646,
    gene_id: 3148,
    gene_symbol: 'HMGB2',
    dsi: 0.615,
    dpi: 0.615,
    disease_id: 'C0152013',
    disease_name: 'Adenocarcinoma of lung (disorder)',
    disease_type: 'disease',
    disease_class: 'C04',
    disease_semantic_type: 'Neoplastic Process',
    score: 0.3,
    ei: 1,
    year_initial: 2014,
    year_final: 2016,
    nof_pmids: 2,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 24647,
    gene_id: 3148,
    gene_symbol: 'HMGB2',
    dsi: 0.615,
    dpi: 0.615,
    disease_id: 'C0376358',
    disease_name: 'Malignant neoplasm of prostate',
    disease_type: 'disease',
    disease_class: 'C04;C12',
    disease_semantic_type: 'Neoplastic Process',
    score: 0.32,
    ei: 1,
    year_initial: 2018,
    year_final: 2019,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 24648,
    gene_id: 3148,
    gene_symbol: 'HMGB2',
    dsi: 0.615,
    dpi: 0.615,
    disease_id: 'C2239176',
    disease_name: 'Liver carcinoma',
    disease_type: 'disease',
    disease_class: 'C06;C04',
    disease_semantic_type: 'Neoplastic Process',
    score: 0.33,
    ei: 1,
    year_initial: 2009,
    year_final: 2018,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9501,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0004352',
    disease_name: 'Autistic Disorder',
    disease_type: 'disease',
    disease_class: 'F03',
    disease_semantic_type: 'Mental or Behavioral Dysfunction',
    score: 0.3,
    ei: 1,
    year_initial: 2019,
    year_final: 2019,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9502,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0008073',
    disease_name: 'Developmental Disabilities',
    disease_type: 'group',
    disease_class: 'F03',
    disease_semantic_type: 'Mental or Behavioral Dysfunction',
    score: 0.3,
    ei: 1,
    year_initial: 2019,
    year_final: 2019,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9503,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0014170',
    disease_name: 'Endometrial Neoplasms',
    disease_type: 'group',
    disease_class: 'C04;C13',
    disease_semantic_type: 'Neoplastic Process',
    score: 0.3,
    ei: 1,
    year_initial: 2012,
    year_final: 2012,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9504,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0036341',
    disease_name: 'Schizophrenia',
    disease_type: 'disease',
    disease_class: 'F03',
    disease_semantic_type: 'Mental or Behavioral Dysfunction',
    score: 0.3,
    ei: 1,
    year_initial: 2011,
    year_final: 2011,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9505,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0085996',
    disease_name: 'Child Development Deviations',
    disease_type: 'disease',
    disease_class: 'F03',
    disease_semantic_type: 'Mental or Behavioral Dysfunction',
    score: 0.3,
    ei: 1,
    year_initial: 2019,
    year_final: 2019,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9506,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0085997',
    disease_name: 'Child Development Disorders, Specific',
    disease_type: 'disease',
    disease_class: 'F03',
    disease_semantic_type: 'Mental or Behavioral Dysfunction',
    score: 0.3,
    ei: 1,
    year_initial: 2019,
    year_final: 2019,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9507,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C0476089',
    disease_name: 'Endometrial Carcinoma',
    disease_type: 'disease',
    disease_class: 'C04;C13',
    disease_semantic_type: 'Neoplastic Process',
    score: 0.33,
    ei: 1,
    year_initial: 2012,
    year_final: 2018,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'CTD_human'
  },
  {
    id: 9508,
    gene_id: 1108,
    gene_symbol: 'CHD4',
    dsi: 0.593,
    dpi: 0.654,
    disease_id: 'C4310688',
    disease_name: 'SIFRIM-HITZ-WEISS SYNDROME',
    disease_type: 'disease',
    disease_class: '',
    disease_semantic_type: 'Disease or Syndrome',
    score: 0.6,
    ei: 1,
    year_initial: 2016,
    year_final: 2016,
    nof_pmids: 2,
    nof_snps: 7,
    source: 'GENOMICS_ENGLAND;UNIPROT'
  },
  {
    id: 65239,
    gene_id: 23019,
    gene_symbol: 'CNOT1',
    dsi: 0.674,
    dpi: 0.577,
    disease_id: 'C0557874',
    disease_name: 'Global developmental delay',
    disease_type: 'disease',
    disease_class: '',
    disease_semantic_type: 'Mental or Behavioral Dysfunction',
    score: 0.4,
    ei: 1,
    year_initial: 2019,
    year_final: 2019,
    nof_pmids: 1,
    nof_snps: 0,
    source: 'GENOMICS_ENGLAND'
  }
];
