export default [
  {
    gene_name: 'ZRSR2',
    genea_claim_name: 'ZRSR2',
    entrez_id: 8233,
    interaction_claim_source: 'OncoKB',
    interaction_type: '',
    drug_claim_name: 'H3B-8800',
    drug_claim_primary_name: 'H3B-8800',
    drug_name: '',
    drug_concept_id: '',
    interaction_group_score: '',
    pmid: ''
  },
  {
    gene_name: 'ZFP36L2',
    genea_claim_name: 'ZFP36L2',
    entrez_id: 678,
    interaction_claim_source: 'NCI',
    interaction_type: '',
    drug_claim_name: 'BUTYRATE',
    drug_claim_primary_name: 'BUTYRATE',
    drug_name: '',
    drug_concept_id: '',
    interaction_group_score: '',
    pmid: 10367403
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'NCI',
    interaction_type: '',
    drug_claim_name: 'FLUOROURACIL',
    drug_claim_primary_name: 'FLUOROURACIL',
    drug_name: 'FLUOROURACIL',
    drug_concept_id: 'chembl:CHEMBL185',
    interaction_group_score: 0.31,
    pmid: 11205264
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'NCI',
    interaction_type: '',
    drug_claim_name: 'S-1',
    drug_claim_primary_name: 'S-1',
    drug_name: '',
    drug_concept_id: '',
    interaction_group_score: '',
    pmid: 16685374
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'PharmGKB',
    interaction_type: '',
    drug_claim_name: 'fluorouracil',
    drug_claim_primary_name: 'fluorouracil',
    drug_name: 'FLUOROURACIL',
    drug_concept_id: 'chembl:CHEMBL185',
    interaction_group_score: 0.31,
    pmid: 24167597
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'PharmGKB',
    interaction_type: '',
    drug_claim_name: 'capecitabine',
    drug_claim_primary_name: 'capecitabine',
    drug_name: 'CAPECITABINE',
    drug_concept_id: 'chembl:CHEMBL1773',
    interaction_group_score: 0.45,
    pmid: 24167597
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'ECGF1',
    entrez_id: 1890,
    interaction_claim_source: 'ChemblInteractions',
    interaction_type: 'inhibitor',
    drug_claim_name: 'CHEMBL65375',
    drug_claim_primary_name: 'TIPIRACIL HYDROCHLORIDE',
    drug_name: 'TIPIRACIL HYDROCHLORIDE',
    drug_concept_id: 'chembl:CHEMBL65375',
    interaction_group_score: 8.12,
    pmid: ''
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'NCI',
    interaction_type: '',
    drug_claim_name: 'MPA',
    drug_claim_primary_name: 'MPA',
    drug_name: 'PROGESTERONE',
    drug_concept_id: 'chembl:CHEMBL103',
    interaction_group_score: 0.21,
    pmid: 12711006
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'NCI',
    interaction_type: '',
    drug_claim_name: 'SULFASALAZINE',
    drug_claim_primary_name: 'SULFASALAZINE',
    drug_name: 'SULFASALAZINE',
    drug_concept_id: 'chembl:CHEMBL421',
    interaction_group_score: 0.56,
    pmid: 15269287
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'BE0002193',
    entrez_id: 1890,
    interaction_claim_source: 'DrugBank',
    interaction_type: 'inhibitor',
    drug_claim_name: 'DB09343',
    drug_claim_primary_name: 'Tipiracil',
    drug_name: 'TIPIRACIL',
    drug_concept_id: 'chembl:CHEMBL235668',
    interaction_group_score: 4.06,
    pmid: ''
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'Thymidine phosphorylase',
    entrez_id: 1890,
    interaction_claim_source: 'TTD',
    interaction_type: '',
    drug_claim_name: 'Uridine',
    drug_claim_primary_name: 'Uridine',
    drug_name: 'URIDINE',
    drug_concept_id: 'chembl:CHEMBL100259',
    interaction_group_score: 0.9,
    pmid: ''
  },
  {
    gene_name: 'TYMP',
    genea_claim_name: 'TYMP',
    entrez_id: 1890,
    interaction_claim_source: 'NCI',
    interaction_type: '',
    drug_claim_name: '5-DEOXY-5-FLUOROURIDINE',
    drug_claim_primary_name: '5-DEOXY-5-FLUOROURIDINE',
    drug_name: '',
    drug_concept_id: '',
    interaction_group_score: '',
    pmid: 11956613
  },
  {
    gene_name: 'TTC37',
    genea_claim_name: 'TTC37',
    entrez_id: 9652,
    interaction_claim_source: 'PharmGKB',
    interaction_type: '',
    drug_claim_name: 'duloxetine',
    drug_claim_primary_name: 'duloxetine',
    drug_name: 'DULOXETINE',
    drug_concept_id: 'chembl:CHEMBL1175',
    interaction_group_score: 5.41,
    pmid: 29407288
  },
  {
    gene_name: 'TRAPPC6B',
    genea_claim_name: 'BE0004276',
    entrez_id: 122553,
    interaction_claim_source: 'DrugBank',
    interaction_type: '',
    drug_claim_name: 'DB08342',
    drug_claim_primary_name: 'S-palmitoyl-L-cysteine',
    drug_name: '',
    drug_concept_id: '',
    interaction_group_score: '',
    pmid: 10592235
  }
]
